# Generated by Django 3.2.15 on 2022-08-19 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profiles_location_skills'),
        ('projects', '0004_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profiles'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'Project')},
        ),
    ]
